### ISSUE TITLE
Changing the folder

### ISSUE THREAD

**Issue by ade-fatimah** [laracademy/generators#15]
Hi!

1. The documentation says to try the below to change the folder, it doesn't work

`php artisan generate:modelfromtable --table=user --folder=app\Models
`
What one gets is a folder named appModel

This is what works :

` php artisan generate:modelfromtable --table=user --folder=app/Models`

2. After generating the folder in the right manner, the changes is not effected in the namespace so irrespective of the fact the structure is now App\Models\User.php, namespace still remains `namespace App`

**Comment by michael-mcmullen** [comment]
You are right... I will need to add a check because for some reason I thought having --namespace as an option would be good enough.

I will add a check to see if the --namespace is left blank but --folder is in there to correct the namespace.

Thanks for reporting it, and sorry for taking so long :(
